### ISSUE TITLE
this.elem.summernote is not a function

### ISSUE THREAD

**Issue by musznik** [rafwell/vue3-summernote-editor#1]
After Copy-Paste code into my code got following error inside console.

 ```
app.js:77229 Uncaught TypeError: this.elem.summernote is not a function
    at Proxy.mounted (app.js:77229)
    at callWithErrorHandling (app.js:16877)
    at callWithAsyncErrorHandling (app.js:16886)
    at Array.hook.__weh.hook.__weh (app.js:12146)
    at flushPostFlushCbs (app.js:17075)
    at render (app.js:15101)
    at mount (app.js:13350)
    at Object.app.mount (app.js:19595)
    at Module../resources/js/app.js (app.js:26127)
    at __webpack_require__ (app.js:84423)
```
Nothing to say more, the most misticial thing in summernote is library import method. How to do it in proper way? 
```
import $ from "jquery";
window.$ = window.jQuery = require('jquery');
import 'summernote';

OR

import $ from 'jquery';
import 'popper.js';
import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';

import CodeMirror from 'codemirror/lib/codemirror';
import 'codemirror/lib/codemirror.css';
import 'codemirror/mode/xml/xml';
import 'codemirror/theme/monokai.css'

import 'summernote/dist/summernote-bs4';
import 'summernote/dist/summernote-bs4.css';

```
and webpack
```
module.exports = {
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            jquery: "jquery",
        }),
    ]
}
```
any suggestions?

_laravel-mix / Vue 3.2.26_

**Comment by rafwell** [comment]
Hi @musznik, here I import using require. `require('summernote')`, I think `import 'summernote';` do the same thing. Look for another errors on console, jquery must be present and summernote too.

**Comment by valadedamien** [comment]
Hi, i see you’re using laravel-mix and vue3, i had the same problem with symfony and vue3. I solved the problem by adding an alias for jquery (jQuery -> jquery).

Exemple alias for encore webpack | Symfony : 

`
.addAliases({
        jQuery: path.resolve(__dirname, "node_modules/jquery")
    })
`

ref: [https://stackoverflow.com/a/69619307/11027923](url)

**Comment by AnthonyScorch** [comment]
Sorry to open this thread up again, exacaly the same issue as above.

> vendor.js?id=778d0042e1eae3746081c1a26dc68486:106439 Uncaught (in promise) TypeError: this.elem.summernote is not a function
>     at Proxy.mounted (vendor.js?id=778d0042e1eae3746081c1a26dc68486:106439:15)
>     at callWithErrorHandling (vendor.js?id=778d0042e1eae3746081c1a26dc68486:10258:22)
>     at callWithAsyncErrorHandling (vendor.js?id=778d0042e1eae3746081c1a26dc68486:10267:21)
>     at hook.__weh.hook.__weh (vendor.js?id=778d0042e1eae3746081c1a26dc68486:12787:29)
>     at flushPostFlushCbs (vendor.js?id=778d0042e1eae3746081c1a26dc68486:10458:47)
>     at render (vendor.js?id=778d0042e1eae3746081c1a26dc68486:16291:9)
>     at mount (vendor.js?id=778d0042e1eae3746081c1a26dc68486:14497:25)
>     at app.mount (vendor.js?id=778d0042e1eae3746081c1a26dc68486:19685:23)
>     at setup (app.js?id=3a2739457665ce0eb701f151b3ed0005:957:174)
>     at vendor.js?id=778d0042e1eae3746081c1a26dc68486:9:9711

jQuery is installed and seems to be aliased fine for my other plugins that use it,

> import $ from 'jquery';
> window.$ = window.jQuery = $;

When attempting to use the SummernoteEditor component however I get the above. I note the statement about importing summernote for yourself but the inclusion of 

> import "summernote" 

throws a compile error due to multiple references.
Trying to work this through with vue but could do with additional requirements that this requires.

**Comment by bernlorbis** [comment]
Not resolve yet
